version: '3.9'

services:
  productsservice:
    image: productsservice
    build:
      context: ./ProductsService
    ports:
      - "5002:80"

  ordersservice:
    image: ordersservice
    build:
      context: ./OrdersService
    ports:
      - "5003:80"
